// Yosys script used:
// read_slang dist/worker_21_1755398283970483997_0/graph_struct_union.sv --top graph_struct_union; prep -top graph_struct_union; fsm_opt; opt_dff -nodffe; opt_reduce; opt_expr; hierarchy; fsm; techmap; opt_expr -fine; opt_clean -purge; opt_demorgan; fsm_map; fsm_extract; opt_dff; fsm_recode; write_verilog -sv -noattr dist/worker_21_1755398283970483997_0/graph_struct_union-Yosys.sv
/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module graph_struct_union(bus_in, clk, inj_data_in_1755398284286_350, inj_sel_in_1755398284286_669, rst, bus_out, inj_data_out_1755398284286_850);
  input [31:0] bus_in;
  wire [31:0] bus_in;
  output [31:0] bus_out;
  wire [31:0] bus_out;
  input clk;
  wire clk;
  wire [31:0] \gen_loop[0].m_inst.out_b ;
  wire [31:0] \gen_loop[1].m_inst.out_b ;
  input [3:0] inj_data_in_1755398284286_350;
  wire [3:0] inj_data_in_1755398284286_350;
  output [7:0] inj_data_out_1755398284286_850;
  wire [7:0] inj_data_out_1755398284286_850;
  input [31:0] inj_sel_in_1755398284286_669;
  wire [31:0] inj_sel_in_1755398284286_669;
  wire [31:0] \m1.out_b ;
  input rst;
  wire rst;
  assign inj_data_out_1755398284286_850[1] = ~inj_data_in_1755398284286_350[1];
  assign inj_data_out_1755398284286_850[5] = ~inj_data_in_1755398284286_350[3];
  assign inj_data_out_1755398284286_850[2] = ~inj_data_in_1755398284286_350[1];
  assign inj_data_out_1755398284286_850[6] = ~inj_data_in_1755398284286_350[3];
  assign inj_data_out_1755398284286_850[3] = ~inj_data_in_1755398284286_350[1];
  assign inj_data_out_1755398284286_850[7] = ~inj_data_in_1755398284286_350[3];
  assign { inj_data_out_1755398284286_850[4], inj_data_out_1755398284286_850[0] } = { inj_data_in_1755398284286_350[2], inj_data_in_1755398284286_350[0] };
  assign bus_out = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
  assign \gen_loop[1].m_inst.out_b [3:0] = { inj_data_out_1755398284286_850[7:5], inj_data_in_1755398284286_350[2] };
  assign \gen_loop[0].m_inst.out_b [3:0] = { inj_data_out_1755398284286_850[3:1], inj_data_in_1755398284286_350[0] };
endmodule
