/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module countbits_ops(in_d, cnt);
  wire [2:0] _00_;
  wire [3:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [1:0] _06_;
  wire [31:0] _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire [31:0] _12_;
  wire [31:0] _13_;
  wire [31:0] _14_;
  output [3:0] cnt;
  wire [3:0] cnt;
  input [7:0] in_d;
  wire [7:0] in_d;
  assign _00_ = _06_ + _10_[0];
  assign _01_ = _00_ + _11_[0];
  assign _02_ = _01_ + _12_[0];
  assign _03_ = _02_ + _13_[0];
  assign _04_ = _03_ + _14_[0];
  assign _05_ = _04_ + _07_[0];
  assign _06_ = 1'h0 + _09_[0];
  assign cnt = _05_ + _08_[0];
  assign _10_[0] = in_d[6] === 1'h1;
  assign _11_[0] = in_d[5] === 1'h1;
  assign _12_[0] = in_d[4] === 1'h1;
  assign _13_[0] = in_d[3] === 1'h1;
  assign _14_[0] = in_d[2] === 1'h1;
  assign _07_[0] = in_d[1] === 1'h1;
  assign _08_[0] = in_d[0] === 1'h1;
  assign _09_[0] = in_d[7] === 1'h1;
  assign _07_[31:1] = 31'h00000000;
  assign _08_[31:1] = 31'h00000000;
  assign _09_[31:1] = 31'h00000000;
  assign _10_[31:1] = 31'h00000000;
  assign _11_[31:1] = 31'h00000000;
  assign _12_[31:1] = 31'h00000000;
  assign _13_[31:1] = 31'h00000000;
  assign _14_[31:1] = 31'h00000000;
endmodule

module top();
  wire _0_;
  wire [3:0] cnt;
  wire [7:0] in_d;
  always @*
    if (1'h1) begin
      assert (_0_);
    end
  assign _0_ = cnt == 3'h6;
  countbits_ops dut (
    .cnt(cnt),
    .in_d(8'h8f)
  );
  assign in_d = 8'h8f;
endmodule
