version: "2"
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - exhaustive
    - gochecknoinits
    - gocritic
    - gocyclo
    - noctx
    - perfsprint
    - protogetter
    - revive
    - sloglint
    - spancheck
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - revive
        text: "var-naming: don't use ALL_CAPS in Go names; use CamelCase"
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
      - linters:
          - staticcheck
        text: "ST1005"
formatters:
  enable:
    - gofumpt
    - goimports
    - gofmt
    - golines
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
