// Yosys script used:
// read_verilog -sv dist/worker_20_1755398283970449279_0/graph_struct_union.sv; prep -top graph_struct_union; fsm_map; opt_demorgan; write_verilog -sv -noattr dist/worker_20_1755398283970449279_0/graph_struct_union-Yosys.sv
/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module ConditionalOps(sel, val_false, val_true, out_val);
  output [31:0] out_val;
  wire [31:0] out_val;
  input sel;
  wire sel;
  input [31:0] val_false;
  wire [31:0] val_false;
  input [31:0] val_true;
  wire [31:0] val_true;
  assign out_val = sel ? val_true : val_false;
endmodule

module graph_struct_union(bus_in, clk, inj_data0_1755398284307_429, inj_data1_1755398284307_798, inj_sel_1755398284308_853, inj_val_false_1755398284317_911, inj_val_true_1755398284317_34, rst, bus_out, inj_data_out_1755398284308_185, inj_out_val_1755398284317_427);
  input [31:0] bus_in;
  wire [31:0] bus_in;
  output [31:0] bus_out;
  wire [31:0] bus_out;
  input clk;
  wire clk;
  wire [31:0] din;
  wire [31:0] dout;
  input [15:0] inj_data0_1755398284307_429;
  wire [15:0] inj_data0_1755398284307_429;
  input [15:0] inj_data1_1755398284307_798;
  wire [15:0] inj_data1_1755398284307_798;
  output [15:0] inj_data_out_1755398284308_185;
  wire [15:0] inj_data_out_1755398284308_185;
  output [31:0] inj_out_val_1755398284317_427;
  wire [31:0] inj_out_val_1755398284317_427;
  input inj_sel_1755398284308_853;
  wire inj_sel_1755398284308_853;
  input [31:0] inj_val_false_1755398284317_911;
  wire [31:0] inj_val_false_1755398284317_911;
  input [31:0] inj_val_true_1755398284317_34;
  wire [31:0] inj_val_true_1755398284317_34;
  input rst;
  wire rst;
  assign inj_data_out_1755398284308_185 = inj_sel_1755398284308_853 ? inj_data1_1755398284307_798 : inj_data0_1755398284307_429;
  ConditionalOps ConditionalOps_inst_1755398284317_8584 (
    .out_val(inj_out_val_1755398284317_427),
    .sel(inj_sel_1755398284308_853),
    .val_false(inj_val_false_1755398284317_911),
    .val_true(inj_val_true_1755398284317_34)
  );
  assign bus_out = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
  assign din = bus_in;
  assign dout = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
endmodule
