// Yosys script used:
// read_slang dist/worker_23_1755422088938230476_0/graph_struct_union.sv --top graph_struct_union; prep -top graph_struct_union; opt_expr; opt_dff; fsm_expand; opt_merge -nomux; opt_lut; write_verilog -sv -noattr dist/worker_23_1755422088938230476_0/graph_struct_union-Yosys.sv
/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module graph_struct_union(bus_in, clk, inj_p_in2_1755422089313_78, inj_p_mode_1755422089313_623, rst, bus_out, inj_p_out_1755422089313_217);
  wire [31:0] _00_;
  wire [31:0] _01_;
  wire [31:0] _02_;
  wire [31:0] _03_;
  wire [31:0] _04_;
  wire [31:0] _05_;
  wire [31:0] _06_;
  wire [31:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input [31:0] bus_in;
  wire [31:0] bus_in;
  output [31:0] bus_out;
  wire [31:0] bus_out;
  input clk;
  wire clk;
  wire [31:0] din;
  wire [31:0] dout;
  input [31:0] inj_p_in2_1755422089313_78;
  wire [31:0] inj_p_in2_1755422089313_78;
  input [1:0] inj_p_mode_1755422089313_623;
  wire [1:0] inj_p_mode_1755422089313_623;
  output [31:0] inj_p_out_1755422089313_217;
  wire [31:0] inj_p_out_1755422089313_217;
  wire [31:0] \more_procedural_inst_1755422089313_5603.p_in1 ;
  wire [31:0] \more_procedural_inst_1755422089313_5603.p_in2 ;
  wire [1:0] \more_procedural_inst_1755422089313_5603.p_mode ;
  wire [31:0] \more_procedural_inst_1755422089313_5603.p_out ;
  input rst;
  wire rst;
  assign _01_ = bus_in + inj_p_in2_1755422089313_78;
  assign _00_ = _07_ + 1'h1;
  assign _03_ = bus_in - inj_p_in2_1755422089313_78;
  assign _04_ = _03_ / 2'h3;
  assign _05_ = { bus_in[27:0], 4'h0 } | inj_p_in2_1755422089313_78[31:2];
  assign _06_ = bus_in ^ inj_p_in2_1755422089313_78;
  assign _07_ = ~ _06_;
  function [31:0] _18_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _18_ = b[31:0];
      3'b?1?:
        _18_ = b[63:32];
      3'b1??:
        _18_ = b[95:64];
      default:
        _18_ = a;
    endcase
  endfunction
  assign inj_p_out_1755422089313_217 = _18_(_00_, { _02_, _04_, _05_ }, { _10_, _09_, _08_ });
  assign _08_ = inj_p_mode_1755422089313_623 == 2'h2;
  assign _09_ = inj_p_mode_1755422089313_623 == 1'h1;
  assign _10_ = ! inj_p_mode_1755422089313_623;
  assign bus_out = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
  assign din = bus_in;
  assign dout = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
  assign \more_procedural_inst_1755422089313_5603.p_in1  = bus_in;
  assign \more_procedural_inst_1755422089313_5603.p_in2  = inj_p_in2_1755422089313_78;
  assign \more_procedural_inst_1755422089313_5603.p_mode  = inj_p_mode_1755422089313_623;
  assign \more_procedural_inst_1755422089313_5603.p_out  = inj_p_out_1755422089313_217;
  assign _02_ = { _01_[30:0], 1'h0 };
endmodule
