// Yosys script used:
// read_verilog -sv dist/worker_23_1755374690506879333_0/graph_struct_union.sv; prep -top graph_struct_union; proc; opt; fsm; opt; memory; opt; techmap; opt; write_verilog -sv -noattr dist/worker_23_1755374690506879333_0/graph_struct_union-Yosys.sv
/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module graph_struct_union(bus_in, clk, inj_data_in_1755374690838_411, inj_en_1755374690838_231, inj_packed_in_1755374690832_418, rst, bus_out, inj_data_out_1755374690838_314, inj_field0_byte_o_1755374690832_197);
  input [31:0] bus_in;
  wire [31:0] bus_in;
  output [31:0] bus_out;
  wire [31:0] bus_out;
  input clk;
  wire clk;
  wire [31:0] din;
  wire [31:0] dout;
  input [7:0] inj_data_in_1755374690838_411;
  wire [7:0] inj_data_in_1755374690838_411;
  output [7:0] inj_data_out_1755374690838_314;
  reg [7:0] inj_data_out_1755374690838_314;
  input inj_en_1755374690838_231;
  wire inj_en_1755374690838_231;
  output [7:0] inj_field0_byte_o_1755374690832_197;
  wire [7:0] inj_field0_byte_o_1755374690832_197;
  input [15:0] inj_packed_in_1755374690832_418;
  wire [15:0] inj_packed_in_1755374690832_418;
  wire [15:0] my_union_var;
  input rst;
  wire rst;
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[0] <= inj_data_in_1755374690838_411[0];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[1] <= inj_data_in_1755374690838_411[1];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[2] <= inj_data_in_1755374690838_411[2];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[3] <= inj_data_in_1755374690838_411[3];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[4] <= inj_data_in_1755374690838_411[4];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[5] <= inj_data_in_1755374690838_411[5];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[6] <= inj_data_in_1755374690838_411[6];
  always_ff @(posedge clk)
    if (inj_en_1755374690838_231) inj_data_out_1755374690838_314[7] <= inj_data_in_1755374690838_411[7];
  assign bus_out = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
  assign din = bus_in;
  assign dout = { bus_in[7:0], bus_in[15:8], bus_in[23:16], bus_in[31:24] };
  assign inj_field0_byte_o_1755374690832_197 = inj_packed_in_1755374690832_418[7:0];
  assign my_union_var = inj_packed_in_1755374690832_418;
endmodule
