// Yosys script used:
// read_verilog -sv dist/worker_27_1755377830205198506_0/countbits_ops.sv; prep -top countbits_ops; fsm_recode; proc; opt_expr -keepdc; fsm_map; fsm_extract; fsm; fsm_expand; write_verilog -sv -noattr dist/worker_27_1755377830205198506_0/countbits_ops-Yosys.sv
/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module BitwiseAssign(in_a, in_b, out_y);
  input [3:0] in_a;
  wire [3:0] in_a;
  input [3:0] in_b;
  wire [3:0] in_b;
  output [3:0] out_y;
  wire [3:0] out_y;
  assign out_y = in_a ^ in_b;
endmodule

module always_multi_stmt_unhandled(in1, in2, out1, out2);
  input [7:0] in1;
  wire [7:0] in1;
  input [7:0] in2;
  wire [7:0] in2;
  output [7:0] out1;
  wire [7:0] out1;
  output [7:0] out2;
  wire [7:0] out2;
  assign out1 = in1;
  assign out2 = in2;
endmodule

module ansi_basic(clk, reset_n);
  input clk;
  wire clk;
  output reset_n;
  wire reset_n;
  assign reset_n = clk;
endmodule

module countbits_ops(clk, in_d, inj_in_a_1755377830619_624, inj_in_a_1755377830739_416, inj_in_a_1755377830741_970, inj_in_b_1755377830619_91, inj_in_b_1755377830741_259, inj_in_c_1755377830619_518, inj_in_cond_neq_lhs_1755377830619_284, inj_in_cond_neq_rhs_1755377830619_112, inj_in_cond_not_1755377830619_249, inj_in_not_else_1755377830619_148, inj_in_not_then_1755377830619_89, inj_in_val_1755377830600_794, inj_in_val_1755377830612_330, inj_select_a_1755377830600_823, rst, cnt, inj_out1_1755377830638_51, inj_out2_1755377830638_704, inj_out_a_1755377830739_235
, inj_out_eq_1755377830619_469, inj_out_eq_concat_1755377830619_327, inj_out_gt_1755377830619_142, inj_out_gte_1755377830619_400, inj_out_lt_1755377830619_799, inj_out_lte_1755377830619_207, inj_out_neq_1755377830619_807, inj_out_not_eq_1755377830619_614, inj_out_not_neq_1755377830619_41, inj_out_ternary_1755377830619_422, inj_out_ternary_1bit_0else_1755377830619_72, inj_out_ternary_1bit_0then_1755377830619_495, inj_out_ternary_1bit_1else_1755377830619_934, inj_out_ternary_1bit_1then_1755377830619_922, inj_out_ternary_const_cond_false_1755377830619_436, inj_out_ternary_const_cond_true_1755377830619_216, inj_out_ternary_dec_1755377830620_875, inj_out_ternary_inc_1755377830620_994, inj_out_ternary_pulled_nots_1755377830620_851, inj_out_ternary_swapped_cond_1755377830620_243, inj_out_ternary_swapped_neq_cond_1755377830620_891
, inj_out_val_1755377830603_909, inj_out_val_1755377830612_351, inj_out_val_1755377831049_224, inj_out_y_1755377830741_755, inj_reset_n_1755377830599_177, inj_sum_1755377830891_369);
  wire [1:0] _00_;
  wire [2:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [3:0] _06_;
  wire [7:0] _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire [31:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire [31:0] _29_;
  wire [31:0] _30_;
  wire [31:0] _31_;
  wire _32_;
  wire [7:0] _33_;
  wire [7:0] _34_;
  wire [7:0] _35_;
  input clk;
  wire clk;
  output [3:0] cnt;
  wire [3:0] cnt;
  input [7:0] in_d;
  wire [7:0] in_d;
  input [7:0] inj_in_a_1755377830619_624;
  wire [7:0] inj_in_a_1755377830619_624;
  input inj_in_a_1755377830739_416;
  wire inj_in_a_1755377830739_416;
  input [3:0] inj_in_a_1755377830741_970;
  wire [3:0] inj_in_a_1755377830741_970;
  input [7:0] inj_in_b_1755377830619_91;
  wire [7:0] inj_in_b_1755377830619_91;
  input [3:0] inj_in_b_1755377830741_259;
  wire [3:0] inj_in_b_1755377830741_259;
  input [7:0] inj_in_c_1755377830619_518;
  wire [7:0] inj_in_c_1755377830619_518;
  input inj_in_cond_neq_lhs_1755377830619_284;
  wire inj_in_cond_neq_lhs_1755377830619_284;
  input inj_in_cond_neq_rhs_1755377830619_112;
  wire inj_in_cond_neq_rhs_1755377830619_112;
  input inj_in_cond_not_1755377830619_249;
  wire inj_in_cond_not_1755377830619_249;
  input [7:0] inj_in_not_else_1755377830619_148;
  wire [7:0] inj_in_not_else_1755377830619_148;
  input [7:0] inj_in_not_then_1755377830619_89;
  wire [7:0] inj_in_not_then_1755377830619_89;
  input [31:0] inj_in_val_1755377830600_794;
  wire [31:0] inj_in_val_1755377830600_794;
  input [31:0] inj_in_val_1755377830612_330;
  wire [31:0] inj_in_val_1755377830612_330;
  output [7:0] inj_out1_1755377830638_51;
  wire [7:0] inj_out1_1755377830638_51;
  output [7:0] inj_out2_1755377830638_704;
  wire [7:0] inj_out2_1755377830638_704;
  output inj_out_a_1755377830739_235;
  wire inj_out_a_1755377830739_235;
  output inj_out_eq_1755377830619_469;
  wire inj_out_eq_1755377830619_469;
  output inj_out_eq_concat_1755377830619_327;
  wire inj_out_eq_concat_1755377830619_327;
  output inj_out_gt_1755377830619_142;
  wire inj_out_gt_1755377830619_142;
  output inj_out_gte_1755377830619_400;
  wire inj_out_gte_1755377830619_400;
  output inj_out_lt_1755377830619_799;
  wire inj_out_lt_1755377830619_799;
  output inj_out_lte_1755377830619_207;
  wire inj_out_lte_1755377830619_207;
  output inj_out_neq_1755377830619_807;
  wire inj_out_neq_1755377830619_807;
  output inj_out_not_eq_1755377830619_614;
  wire inj_out_not_eq_1755377830619_614;
  output inj_out_not_neq_1755377830619_41;
  wire inj_out_not_neq_1755377830619_41;
  output inj_out_ternary_1755377830619_422;
  wire inj_out_ternary_1755377830619_422;
  output inj_out_ternary_1bit_0else_1755377830619_72;
  wire inj_out_ternary_1bit_0else_1755377830619_72;
  output inj_out_ternary_1bit_0then_1755377830619_495;
  wire inj_out_ternary_1bit_0then_1755377830619_495;
  output inj_out_ternary_1bit_1else_1755377830619_934;
  wire inj_out_ternary_1bit_1else_1755377830619_934;
  output inj_out_ternary_1bit_1then_1755377830619_922;
  wire inj_out_ternary_1bit_1then_1755377830619_922;
  output inj_out_ternary_const_cond_false_1755377830619_436;
  wire inj_out_ternary_const_cond_false_1755377830619_436;
  output inj_out_ternary_const_cond_true_1755377830619_216;
  wire inj_out_ternary_const_cond_true_1755377830619_216;
  output [7:0] inj_out_ternary_dec_1755377830620_875;
  wire [7:0] inj_out_ternary_dec_1755377830620_875;
  output [7:0] inj_out_ternary_inc_1755377830620_994;
  wire [7:0] inj_out_ternary_inc_1755377830620_994;
  output [7:0] inj_out_ternary_pulled_nots_1755377830620_851;
  wire [7:0] inj_out_ternary_pulled_nots_1755377830620_851;
  output inj_out_ternary_swapped_cond_1755377830620_243;
  wire inj_out_ternary_swapped_cond_1755377830620_243;
  output inj_out_ternary_swapped_neq_cond_1755377830620_891;
  wire inj_out_ternary_swapped_neq_cond_1755377830620_891;
  output [31:0] inj_out_val_1755377830603_909;
  wire [31:0] inj_out_val_1755377830603_909;
  output [31:0] inj_out_val_1755377830612_351;
  wire [31:0] inj_out_val_1755377830612_351;
  output [31:0] inj_out_val_1755377831049_224;
  wire [31:0] inj_out_val_1755377831049_224;
  output [3:0] inj_out_y_1755377830741_755;
  wire [3:0] inj_out_y_1755377830741_755;
  output inj_reset_n_1755377830599_177;
  wire inj_reset_n_1755377830599_177;
  input inj_select_a_1755377830600_823;
  wire inj_select_a_1755377830600_823;
  output [3:0] inj_sum_1755377830891_369;
  wire [3:0] inj_sum_1755377830891_369;
  wire [15:0] intermediate_concat_comp_src_ts1755377830634;
  wire [7:0] intermediate_const_concat_comp_ts1755377830634;
  input rst;
  wire rst;
  assign _00_ = 1'h0 + _08_[0];
  assign _01_ = _00_ + _09_[0];
  assign _02_ = _01_ + _10_[0];
  assign _03_ = _02_ + _11_[0];
  assign _04_ = _03_ + _29_[0];
  assign _05_ = _04_ + _30_[0];
  assign _06_ = _05_ + _31_[0];
  assign inj_sum_1755377830891_369 = inj_in_a_1755377830741_970 + inj_in_b_1755377830741_259;
  assign _07_ = inj_in_a_1755377830619_624 + 1'h1;
  assign cnt = _06_ + _12_[0];
  assign inj_out_eq_1755377830619_469 = inj_in_a_1755377830619_624 == inj_in_b_1755377830619_91;
  assign inj_out_eq_concat_1755377830619_327 = 8'haa == inj_in_b_1755377830619_91;
  assign _13_ = in_d[7] === 1'h1;
  assign _14_ = in_d[7] === 1'hx;
  assign _15_ = in_d[6] === 1'h1;
  assign _16_ = in_d[6] === 1'hx;
  assign _17_ = in_d[5] === 1'h1;
  assign _18_ = in_d[5] === 1'hx;
  assign _19_ = in_d[4] === 1'h1;
  assign _20_ = in_d[4] === 1'hx;
  assign _21_ = in_d[3] === 1'h1;
  assign _22_ = in_d[3] === 1'hx;
  assign _23_ = in_d[2] === 1'h1;
  assign _24_ = in_d[2] === 1'hx;
  assign _25_ = in_d[1] === 1'h1;
  assign _26_ = in_d[1] === 1'hx;
  assign _27_ = in_d[0] === 1'h1;
  assign _28_ = in_d[0] === 1'hx;
  assign inj_out_gte_1755377830619_400 = inj_in_a_1755377830619_624 >= inj_in_b_1755377830619_91;
  assign inj_out_gt_1755377830619_142 = inj_in_a_1755377830619_624 > inj_in_b_1755377830619_91;
  assign inj_out_lte_1755377830619_207 = inj_in_a_1755377830619_624 <= inj_in_b_1755377830619_91;
  assign inj_out_not_eq_1755377830619_614 = ! inj_out_eq_1755377830619_469;
  assign inj_out_not_neq_1755377830619_41 = ! inj_out_neq_1755377830619_807;
  assign _08_[0] = _13_ || _14_;
  assign _09_[0] = _15_ || _16_;
  assign _10_[0] = _17_ || _18_;
  assign _11_[0] = _19_ || _20_;
  assign _29_[0] = _21_ || _22_;
  assign _30_[0] = _23_ || _24_;
  assign _31_[0] = _25_ || _26_;
  assign _12_[0] = _27_ || _28_;
  assign inj_out_lt_1755377830619_799 = inj_in_a_1755377830619_624 < inj_in_b_1755377830619_91;
  assign inj_out_neq_1755377830619_807 = inj_in_a_1755377830619_624 != inj_in_b_1755377830619_91;
  assign _32_ = inj_in_cond_neq_lhs_1755377830619_284 != inj_in_cond_neq_rhs_1755377830619_112;
  assign _33_ = ~ inj_in_not_then_1755377830619_89;
  assign _34_ = ~ inj_in_not_else_1755377830619_148;
  assign _35_ = inj_in_a_1755377830619_624 - 1'h1;
  assign inj_out_ternary_1755377830619_422 = rst ? inj_in_a_1755377830619_624[0] : inj_in_b_1755377830619_91[0];
  assign inj_out_ternary_swapped_cond_1755377830620_243 = inj_in_cond_not_1755377830619_249 ? inj_in_b_1755377830619_91[0] : inj_in_a_1755377830619_624[0];
  assign inj_out_ternary_swapped_neq_cond_1755377830620_891 = _32_ ? inj_in_a_1755377830619_624[0] : inj_in_b_1755377830619_91[0];
  assign inj_out_ternary_pulled_nots_1755377830620_851 = rst ? _33_ : _34_;
  assign inj_out_ternary_inc_1755377830620_994 = rst ? _07_ : inj_in_a_1755377830619_624;
  assign inj_out_ternary_dec_1755377830620_875 = rst ? _35_ : inj_in_a_1755377830619_624;
  assign inj_out_ternary_1bit_0then_1755377830619_495 = rst ? 1'h0 : clk;
  assign inj_out_ternary_1bit_1then_1755377830619_922 = rst ? 1'h1 : clk;
  assign inj_out_ternary_1bit_0else_1755377830619_72 = rst ? clk : 1'h0;
  assign inj_out_ternary_1bit_1else_1755377830619_934 = rst ? clk : 1'h1;
  BitwiseAssign BitwiseAssign_inst_1755377830741_1827 (
    .in_a(inj_in_a_1755377830741_970),
    .in_b(inj_in_b_1755377830741_259),
    .out_y(inj_out_y_1755377830741_755)
  );
  always_multi_stmt_unhandled always_multi_stmt_unhandled_inst_1755377830638_7020 (
    .in1(in_d),
    .in2(8'haa),
    .out1(inj_out1_1755377830638_51),
    .out2(inj_out2_1755377830638_704)
  );
  ansi_basic ansi_basic_inst_1755377830599_7939 (
    .clk(clk),
    .reset_n(inj_reset_n_1755377830599_177)
  );
  member_access_packed_union member_access_packed_union_inst_1755377830603_6965 (
    .in_val(inj_in_val_1755377830600_794),
    .out_val(inj_out_val_1755377830603_909),
    .select_a(inj_select_a_1755377830600_823)
  );
  mod_name_conflict mod_name_conflict_inst_1755377830739_4024 (
    .in_a(inj_in_a_1755377830739_416),
    .out_a(inj_out_a_1755377830739_235)
  );
  simple_undeclared_mod simple_undeclared_mod_inst_1755377830612_4898 (
    .in_val(inj_in_val_1755377830612_330),
    .out_val(inj_out_val_1755377830612_351)
  );
  assign _08_[31:1] = 31'h00000000;
  assign _09_[31:1] = 31'h00000000;
  assign _10_[31:1] = 31'h00000000;
  assign _11_[31:1] = 31'h00000000;
  assign _12_[31:1] = 31'h00000000;
  assign _29_[31:1] = 31'h00000000;
  assign _30_[31:1] = 31'h00000000;
  assign _31_[31:1] = 31'h00000000;
  assign inj_out_ternary_const_cond_false_1755377830619_436 = inj_in_b_1755377830619_91[0];
  assign inj_out_ternary_const_cond_true_1755377830619_216 = inj_in_a_1755377830619_624[0];
  assign inj_out_val_1755377831049_224 = inj_in_val_1755377830612_330;
  assign intermediate_concat_comp_src_ts1755377830634 = { inj_in_a_1755377830619_624, inj_in_b_1755377830619_91 };
  assign intermediate_const_concat_comp_ts1755377830634 = 8'haa;
endmodule

module member_access_packed_union(in_val, select_a, out_val);
  input [31:0] in_val;
  wire [31:0] in_val;
  output [31:0] out_val;
  wire [31:0] out_val;
  input select_a;
  wire select_a;
  wire [31:0] union_var;
  assign out_val = in_val;
  assign union_var = in_val;
endmodule

module mod_name_conflict(in_a, out_a);
  input in_a;
  wire in_a;
  output out_a;
  wire out_a;
  assign out_a = in_a;
endmodule

module simple_undeclared_mod(in_val, out_val);
  input [31:0] in_val;
  wire [31:0] in_val;
  output [31:0] out_val;
  wire [31:0] out_val;
  assign out_val = in_val;
endmodule
