/* Generated by Yosys 0.53+60 (git sha1 3790be114, g++ 12.2.0-14+deb12u1 -fPIC -O3) */

(* cells_not_processed =  1  *)
(* src = "../stmt_if_task.sv:1.1-19.10" *)
module stmt_if_task(out_val_m6, in_val_m6, condition_m6);
  (* src = "../stmt_if_task.sv:4.15-4.27" *)
  input condition_m6;
  wire condition_m6;
  (* src = "../stmt_if_task.sv:3.23-3.32" *)
  input [7:0] in_val_m6;
  wire [7:0] in_val_m6;
  (* src = "../stmt_if_task.sv:2.24-2.34" *)
  output [7:0] out_val_m6;
  wire [7:0] out_val_m6;
  (* nosync = 32'd1 *)
  (* src = "../stmt_if_task.sv:7.52-7.56" *)
  wire \update_conditional_m6$func$../stmt_if_task.sv:16$1.cond ;
  (* nosync = 32'd1 *)
  (* src = "../stmt_if_task.sv:7.76-7.79" *)
  wire [7:0] \update_conditional_m6$func$../stmt_if_task.sv:16$1.val ;
  (* src = "../stmt_if_task.sv:6.17-6.23" *)
  wire [7:0] var_m6;
  assign out_val_m6 = in_val_m6;
  assign \update_conditional_m6$func$../stmt_if_task.sv:16$1.cond  = 1'hx;
  assign \update_conditional_m6$func$../stmt_if_task.sv:16$1.val  = 8'hxx;
  assign var_m6 = in_val_m6;
endmodule
