/* Generated by Yosys 0.51+46 (git sha1 8bde6ac17, g++ 12.2.0-14 -fPIC -O3) */

module expr_postsub_comb(in_val_m2, sub_val_m2, out_diff_m2, var_out_m2);
  wire [7:0] _0_;
  wire [7:0] _1_;
  input [7:0] in_val_m2;
  wire [7:0] in_val_m2;
  output [7:0] out_diff_m2;
  wire [7:0] out_diff_m2;
  input [7:0] sub_val_m2;
  wire [7:0] sub_val_m2;
  wire [7:0] var_m2;
  output [7:0] var_out_m2;
  wire [7:0] var_out_m2;
  assign _0_ = in_val_m2 - 2'h1;
  assign _1_ = _0_ - sub_val_m2;
  assign out_diff_m2 = _1_;
  assign var_out_m2 = _0_;
  assign var_m2 = _0_;
endmodule
