/* Generated by Yosys 0.51+46 (git sha1 8bde6ac17, g++ 12.2.0-14 -fPIC -O3) */

module expr_postsub_comb(in_val_m2, sub_val_m2, out_diff_m2, var_out_m2);
  reg [7:0] _0_;
  reg [7:0] _1_;
  reg [7:0] _2_;
  wire [31:0] _3_;
  wire [7:0] _4_;
  wire [7:0] _5_;
  input [7:0] in_val_m2;
  wire [7:0] in_val_m2;
  output [7:0] out_diff_m2;
  reg [7:0] out_diff_m2;
  input [7:0] sub_val_m2;
  wire [7:0] sub_val_m2;
  reg [7:0] var_m2;
  output [7:0] var_out_m2;
  reg [7:0] var_out_m2;
  assign _3_ = in_val_m2 - 32'd1;
  assign _4_ = _3_[7:0] - 1'h1;
  assign _5_ = _4_ - sub_val_m2;
  always_comb begin
    _1_ = _3_[7:0];
    _0_ = _5_;
    _2_ = _3_[7:0];
  end
  always_comb begin
      out_diff_m2 <= _0_;
      var_out_m2 <= _2_;
      var_m2 <= _1_;
  end
endmodule
