name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.20" # Specify the Go version you need

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog verilator

      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest # Using latest, as v2.1.5 is not a standard golangci-lint version format. Adjust if needed.

      - name: Vet Go Code
        run: go vet ./...

      - name: Check Go Formatting
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Go code is not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Build
        run: |
          make build
          if [ $? -ne 0 ]; then
            echo "Make build failed"
            exit 1
          fi

      - name: Run
        run: |
          make run
          if [ $? -ne 0 ]; then
            echo "Make run failed"
            exit 1
          fi
      - name: Test
        run: |
          make tests
          if [ $? -ne 0 ]; then
            echo "Make tests failed"
            exit 1
          fi
