// Yosys script used:
// read_verilog -sv dist/worker_9_1755425167224819387_0/m_caseeq_demo.sv; prep -top m_caseeq_demo; opt_mem; write_verilog -sv -noattr dist/worker_9_1755425167224819387_0/m_caseeq_demo-Yosys.sv
/* Generated by Yosys 0.55+23 (git sha1 e57a2b944, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module m_caseeq_demo(clk, in, inj_i_target_data_1755425167519_276, rst, eq, inj_o_target_result_1755425167519_359, neq);
  input clk;
  wire clk;
  output eq;
  wire eq;
  input in;
  wire in;
  input [7:0] inj_i_target_data_1755425167519_276;
  wire [7:0] inj_i_target_data_1755425167519_276;
  output [7:0] inj_o_target_result_1755425167519_359;
  wire [7:0] inj_o_target_result_1755425167519_359;
  output neq;
  wire neq;
  input rst;
  wire rst;
  wire tri_sig;
  assign inj_o_target_result_1755425167519_359 = inj_i_target_data_1755425167519_276 + 1'h1;
  assign eq = in === 1'hz;
  assign neq = in !== 1'hz;
  assign tri_sig = 1'hz;
endmodule
